### PR TITLE
Merge with ARM image builder from raspbian with debian-jessie

### PR DESCRIPTION
**Pull request by Sylvain303**
Hi,

So cool script to rebuild a new image. May be to add somewhere else.
Let me know.

Regards.

### CODE REVIEW

**Comment by M5oul** [comment]
Hi @Sylvain303,

Thanks for this helpfull scripts.
I read it and try it a bit with [an ARMbian image](http://armbian.com/).
It's not really working. That's normal.

I think you should use an other repository for building ARM images.
You could name it `build_arm_images`.
I could add it to YunoHost projects repositories.

That way, I could contribute and make it works with ARMbian images.

Thanks.

**Comment by alexAubin** [comment]
This is great work but it looks outdated (PR is more than 1 year old) ... Nowadays we have https://github.com/likeitneverwentaway/rpi_buildbot and trotinette... Shall we merge this or close ? I went through the README and it looks like there are a few relevant elements which should be taken into consideration though...

**Comment by alexAubin** [comment]
(Wrong button :/)

**Comment by Sylvain303** [comment]
What are you waiting for me to do or tell?

I didn't followed any yunohost works since. Those script work, I used them for pushing the latest raspbian to a sd card, I don't know tools you mentioned. 

You can do whatever you decide on this, it's free for all. :)

**Comment by alexAubin** [comment]
@Sylvain303 Sorry if you felt like this was an agressive comment, this was more intended as a call for comments to the yunohost team, but thanks for giving your feedback also :D

**Comment by Sylvain303** [comment]
It's OK, no hurt. :)

Ask, if I've time, I will do something… ;)

**Comment by alexAubin** [comment]
Ok guys, sorry about this PR but in fact I don't think that the install_script repo is the good place to have the code that produces the image ... Plus in fact I ended up using Raspbian's build code to build custom images for Stretch and the future, that should be way more robust and easier to maintain than having our custom code : https://github.com/YunoHost/rpi-image

So I'm closing this, sorry again for the lack of activity / feedback on this PR from our side :confused:

**Pull request closed without merging**
