### PR TITLE
Add tip on how to remove conflciting packages like bind9 and apache

### PR DESCRIPTION
**Pull request by alexAubin**
Follow up of https://github.com/YunoHost/doc/pull/1053

### CODE REVIEW

**Comment by SuperSandro2000** [comment]
This should probably use ``apt autoremove``

**Comment by alexAubin** [comment]
Uh what do you mean ? `apt autoremove` is usually meant to remove unused dependencies ?

**Comment by SuperSandro2000** [comment]
Yeah, it would also purge dependencies of bind9 and apache.

**Comment by decentral1se** [comment]
Pass `--autoremove` then too?

**Pull request merged**
